### ISSUE TITLE
Should the grid broker wait X number of verification of a block before processing a reservation

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/grid_broker#8]

**Comment by LeeSmet** [comment]
While it is safer to wait technically spaking, any transaction which makes it into the pool should be accepted eventually. Waiting for about 6 blocks or so would add security in case of forks, but for a regular money transaction it is very unlikely that the tx would dissapear in case of a small fork, since as long as the block creator is connected to the network it will receive the tx, and monetary txes should be valid on both forks (unless at some point it did not include a tx in the fork, but in case it is a connected blockcreator that would mean its malicious. Also not including txes makes the chain lighter compaired to the other forks, giving less incentive to the network to actually switch to this fork). Also waiting for the block confirmations adds some bad UX, so at this point its more of a question if we need the added security, and can trade the worse UX for that

**Comment by zaibon** [comment]
For now, we'll accept the unconfirmed transactions. Let's see how it goes like that.
https://github.com/threefoldtech/grid_broker/commit/13ddd8cb7bce0c2edd4dcb830038e6b4d2d859cb
